[package]
name = "capsule-rtp"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
capsule = "0.1.5"
rtp-rs = "0.6.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
